import Image from "next/image";
import Link from "next/link";
import React from "react";

import BlogNav from "./blog_nav"
import Settings from "./settings";

const BlogLayout = ({ children }) => {
    return (
        <div className="blog">
            <BlogNav></BlogNav>
            <Settings blog="true"></Settings>
            <div className="main">
                {children}
            </div>
            
            <footer>
                <h2>
                    Ishan Writes 2023
                </h2>
                <p>
                    Intellectual property of <Link href="/">Ishan Joshi</Link> | Website licensed under MIT
                </p>
                <small>My thoughts and opinions are my own | </small>
                <small>Some Images might be generated by AI</small>
                <p></p>
                <a href="https://notbyai.fyi"><Image src="/assets/not_ai.svg" className="normal-img" style={{ padding: "0 12px"}} width="32" height="32" alt="Not Written by an AI" /></a>
                <Link href="/license">
                    <Image src="/assets/mit.svg" className="normal-img" width="32" height="32" alt="Mit License" />
                </Link>
            </footer>
        </div>
    )
}

export default BlogLayout