import React from "react";

import Layout from "@/components/layout";
import { Seo } from "@/components/seo"
import Link from "next/link";
import TypeWriter from "@/components/typewriter";

// import light_pfp from "@/static/images/profile-light.webp"
// import dark_pfp from "@/static/images/profile-dark.webp"
// import Image from "next/image";

const Home = () => {
    const scroll = () => {
        window.scrollTo({
            top: document.getElementById('intro').offsetTop,
            behavior: "smooth"
        });
    }
    const does = ["Student at GRIET", "Full Stack Developer", "Opinionated Writer", "Open Source Enthusiast", "Always on GitHub", "Loves Dogs"];
    return (
        <Layout>
            <div className="hero">
                <h1 style={{padding: "0 0 2rem 0",}} className="index-title">
                    <span>{/* eslint-disable-next-line */}
                        {/* <img src={light_pfp.src} alt="Light Profile Picture" className="light-pfp profile-pic" /> */}
                        {/* eslint-disable-next-line */}
                        {/* <img src={dark_pfp.src} alt="Dark Profile Picture" className="dark-pfp profile-pic" /> */}
                    </span><p></p>
                    <span style={{ color: "var(--blue)", }}>I</span>shan <span style={{ color: "var(--green)", }}>J</span>oshi
                </h1>
                <TypeWriter data={does} />
                <h2 className="sub_title"><Link href="/about" style={{ background: "#75f0f3" }}>Student</Link><Link href="/skills" style={{ background: "#95ee65" }}>Full Stack Dev</Link><Link href="/projects" style={{ background: "#f888d6" }}>Open Source</Link></h2>
                <h2 className="m_sub_title"><Link href="/about" style={{ background: "#75f0f3", borderRadius: "12px", padding: "12px", margin: "40px" }}>Student</Link></h2>
                <h2 className="m_sub_title"><Link href="/skills" style={{ background: "#95ee65", borderRadius: "12px", padding: "12px" }}>Full Stack</Link></h2>
                <h2 className="m_sub_title"><Link href="/projects" style={{ background: "#f888d6", borderRadius: "12px", padding: "12px" }}>Open Source</Link></h2>
                <div style={{ textAlign: "center" }}>
                    <button onClick={scroll} className='scroll_btn'><i className="bi bi-chevron-compact-down"></i></button>
                </div>
            </div>
            <div id='intro' style={{ backgroundColor: "var(--green)" }} className='color-div'>
                <div className="hero_vid">
                    <video src="/assets/hero_vid.mp4" autoPlay loop muted></video>
                    <small>AI Generated by Microsoft Designer</small>
                </div>
                <div className="vid_hero">
                    <h1>Hello! Do you know me?</h1>
                    <p>
                        Hi! I am a student and a full stack developer. I love to code and I love to learn new things.
                        I am primarily a web developer and I love to work with React and python.
                        I started programming about 3 years ago and never looked back since.
                        Well, living in the terminal is my thing and I love to work with linux.
                        I started my journey with python and then moved to web development.
                        I am currently learning different Javascript frameworks and I am loving it.
                        I am also a big fan of open source and I love to contribute to open source projects.
                    </p>
                    <button style={{ backgroundColor: "var(--violet)", }} className="link-btn"><Link href="/about">Read More About Me</Link></button>
                </div>
            </div>
            <div style={{ backgroundColor: "var(--yellow)", }} id="sitemap" className="color-div">
                <h2>
                    Just a quick sitemap for easy navigation
                </h2>
                <ul>
                    <li><Link href="/about">About Me</Link></li>
                    <li><Link href="/skills">Skills</Link></li>
                    <li><Link href="/projects">Projects</Link></li>
                    <li><Link href="/blog">Blog</Link></li>
                    <li><Link href="/skills">My Skills</Link></li>
                    <li>
                        <Link href="/github">GitHub</Link>
                    </li>
                    <li>
                        <Link href="/social">My Social Links</Link>
                    </li>
                    <li>
                        <Link href="/resume">My Resume</Link>
                    </li>
                    <li>
                        <Link href="/tools">Tools</Link>
                    </li>
                </ul>
            </div>
            <div style={{ backgroundColor: "var(--white)", }} className="color-div">
                <h2>
                    📌 Updates Board
                </h2>
                <div className="bod">
                    <h3>
                        Not to brag, but see this lighthouse score!
                    </h3>
                    <div className="img">
                        <img src="/assets/site/lighthouse.png" alt="LightHouse Score" />
                    </div>
                    <p>
                        I have been working on my website for a while now and I am really happy with the results.
                        The lighthouse score is always in between 90-100.
                        Now I am treating this as an achievement because, this site also hosts a blog that has 
                        costly images and videos. I am just glad that I was able to achieve this score.
                    </p>
                </div>
            </div>
        </Layout>
    )
}

export const Head = () => {
    return (
        <Seo title="NoobScience | Student and Open Source Enthusiast" description="Home Page" />
    )
}

export default Home